name: Deploy to Heroku using OAuth

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Heroku using OAuth
        env:
          HEROKU_CLIENT_ID: ${{ secrets.HEROKU_CLIENT_ID }}
          HEROKU_CLIENT_SECRET: ${{ secrets.HEROKU_CLIENT_SECRET }}
        run: |
          # استخدام بيانات OAuth لتسجيل الدخول
          curl -n -X POST https://id.heroku.com/oauth/token \
          -d "grant_type=client_credentials" \
          -d "client_id=${{ secrets.HEROKU_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.HEROKU_CLIENT_SECRET }}" \
          -d "scope=global"
          echo "Logged in with OAuth!"

      - name: Deploy to Heroku
        run: git push https://git.heroku.com/<heroku-app-name>.git master
